# Generated by Django 2.0.6 on 2018-06-08 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_storage', models.BooleanField(default=True)),
                ('money_left', models.DecimalField(decimal_places=8, max_digits=30, verbose_name='余额')),
                ('open_date', models.DateTimeField(auto_now_add=True, verbose_name='开户日期')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='最近访问')),
                ('overdraft', models.DecimalField(decimal_places=8, max_digits=30, verbose_name='透支额')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('tel_num', models.CharField(max_length=30, verbose_name='联系电话')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('relation', models.CharField(max_length=20, verbose_name='联系人关系')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='身份证ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('tel_num', models.CharField(max_length=30, verbose_name='联系电话')),
                ('home_addr', models.CharField(max_length=100, verbose_name='家庭住址')),
                ('check_accounts', models.ManyToManyField(blank=True, null=True, related_name='owners', related_query_name='owner', to='bankapp.CheckAccount')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bankapp.ContactInfo', verbose_name='联系人信息')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=5, max_digits=25, verbose_name='贷款金额')),
            ],
        ),
        migrations.CreateModel(
            name='PayRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=5, max_digits=25, verbose_name='支付金额')),
                ('paydate', models.DateField(auto_now_add=True)),
                ('related_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_records', related_query_name='pay_record', to='bankapp.Loan')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('home_addr', models.CharField(max_length=100, verbose_name='家庭住址')),
                ('tel_num', models.CharField(max_length=30, verbose_name='联系电话')),
                ('hire_date', models.DateField(auto_now_add=True, verbose_name='雇佣日期')),
            ],
        ),
        migrations.CreateModel(
            name='StorageAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_storage', models.BooleanField(default=True)),
                ('money_left', models.DecimalField(decimal_places=8, max_digits=30, verbose_name='余额')),
                ('open_date', models.DateTimeField(auto_now_add=True, verbose_name='开户日期')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='最近访问')),
                ('interest_rate', models.DecimalField(decimal_places=5, max_digits=6, verbose_name='利率')),
                ('money_type', models.CharField(max_length=30, verbose_name='货币类型')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('staff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='bankapp.Staff')),
                ('staff_id', models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='身份证ID')),
            ],
            bases=('bankapp.staff',),
        ),
        migrations.AddField(
            model_name='storageaccount',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storage_accounts', related_query_name='storage_account', to='bankapp.SubBank', verbose_name='所属支行'),
        ),
        migrations.AddField(
            model_name='staff',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staffs', related_query_name='staff', to='bankapp.SubBank', verbose_name='工作支行'),
        ),
        migrations.AddField(
            model_name='staff',
            name='mgr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_staffs', related_query_name='sub_staff', to='bankapp.Staff', verbose_name='上级经理'),
        ),
        migrations.AddField(
            model_name='customer',
            name='loans',
            field=models.ManyToManyField(blank=True, null=True, related_name='owners', related_query_name='owner', to='bankapp.Loan', verbose_name='拥有贷款'),
        ),
        migrations.AddField(
            model_name='customer',
            name='relation_staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_customers', related_query_name='related_customer', to='bankapp.Staff', verbose_name='联系员工'),
        ),
        migrations.AddField(
            model_name='customer',
            name='storage_accounts',
            field=models.ManyToManyField(blank=True, null=True, related_name='owners', related_query_name='owner', to='bankapp.StorageAccount'),
        ),
        migrations.AddField(
            model_name='checkaccount',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='check_accounts', related_query_name='check_account', to='bankapp.SubBank', verbose_name='所属支行'),
        ),
    ]
