# Generated by Django 2.0.6 on 2018-06-08 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='hire_date',
            field=models.DateField(default=datetime.date.today, verbose_name='雇佣日期'),
        ),
    ]
