# Generated by Django 2.0.6 on 2018-06-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_auto_20180608_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='check_accounts',
            field=models.ManyToManyField(blank=True, null=True, related_name='owners', related_query_name='owners', to='bankapp.CheckAccount'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='loans',
            field=models.ManyToManyField(blank=True, null=True, related_name='owners', related_query_name='owners', to='bankapp.Loan', verbose_name='拥有贷款'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='storage_accounts',
            field=models.ManyToManyField(blank=True, null=True, related_name='owners', related_query_name='owners', to='bankapp.StorageAccount'),
        ),
    ]
