# Generated by Django 2.0.6 on 2018-06-10 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_auto_20180610_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkaccount',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='check_accounts', to='bankapp.SubBank', verbose_name='所属支行'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='check_accounts',
            field=models.ManyToManyField(blank=True, null=True, related_name='owners', to='bankapp.CheckAccount'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='relation_staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_customers', to='bankapp.Staff', verbose_name='联系员工'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='storage_accounts',
            field=models.ManyToManyField(blank=True, null=True, related_name='owners', to='bankapp.StorageAccount'),
        ),
        migrations.AlterField(
            model_name='payrecord',
            name='related_loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_records', to='bankapp.Loan'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staffs', to='bankapp.SubBank', verbose_name='工作支行'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='mgr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_staffs', to='bankapp.Staff', verbose_name='上级经理'),
        ),
        migrations.AlterField(
            model_name='storageaccount',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storage_accounts', to='bankapp.SubBank', verbose_name='所属支行'),
        ),
    ]
