# Generated by Django 2.0.6 on 2018-06-11 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_auto_20180610_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkaccount',
            name='is_storage',
        ),
        migrations.RemoveField(
            model_name='storageaccount',
            name='is_storage',
        ),
    ]
