# Generated by Django 2.0.6 on 2018-06-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_auto_20180611_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='loans',
        ),
        migrations.AddField(
            model_name='loan',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owners', related_query_name='owners', to='bankapp.Customer', verbose_name='所属用户'),
        ),
    ]
