# Generated by Django 2.0.6 on 2018-06-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0006_auto_20180611_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrecord',
            name='paydate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
