# Generated by Django 2.0.6 on 2018-06-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0007_auto_20180611_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='money_returned',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=25, verbose_name='已还金额'),
        ),
    ]
