# Generated by Django 2.0.6 on 2018-06-11 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0008_loan_money_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrecord',
            name='paydate',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
