# Generated by Django 2.0.6 on 2018-06-11 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0009_auto_20180611_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrecord',
            name='paydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 11, 14, 46, 11, 965809)),
        ),
    ]
