# Generated by Django 2.0.6 on 2018-06-12 02:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0010_auto_20180611_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrecord',
            name='paydate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
